name: CD

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.23.0"  # Replace with the required Go version

    # Step 3: Build the application
    - name: Build app
      run: ./scripts/buildprod.sh

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Use gcloud CLI
      run: gcloud info

    - name: Build and Push Docker Image
      run: gcloud builds submit --tag us-east1-docker.pkg.dev/notely-445102/notely-ar-repo/my-app-image:latest .

    - name: Deploy to Cloud Run
      run: gcloud run deploy notely --image us-east1-docker.pkg.dev/notely-445102/notely-ar-repo/my-app-image:latest --region us-central1 --allow-unauthenticated --project notely-445102 --max-instances=4
