name: CD

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.23.0"  # Replace with the required Go version

    # Step 3: Build the application
    - name: Build the application
      run: ./scripts/buildprod.sh
